version: "3.9"
services:
  worker:
    build: .
    environment:
      HNDLR: 
      SESSION_NAME: BAA4W-kiAxyob8R0aieA588bCtMQtoAd-XoxUqqCAE5JvUjE3uBV5EahWA3JUuZvz5VCO0LzCORLhi5DfPKWjVUGMSM4GXZJhoHXpe5gjS4ht2U1BvddhGFPzzFRslC0V5J-MyNUN-3IwxASJKWuAZxcTVg1OVxY-reXpyrG_T0zDRfE8M9HGBgeGcAsNMF2bbGcMZYgb5IQaaRkzzl330RWUKPL5zhOOf9m7T1pKwyIInWFIFtJR9F0EykW3FN4IzSP898cu1yox7V8RokepjdguY-9y4-GcjOkp1wBp0XBW3MNaAdSMDeu-VF6EZ41IjadmbSyUrF8yReT8W3PVbSLAAAAATwVKHsA
      API_ID: 9457554
      API_HASH:  afe6fa185f76cf358f9435ae6296d7ac
      SUDO_USERS: 5305593604
      UPDATES_CHANNEL: T_8_T_t
      BOT_TOKEN: 5249933311:AAFIdNkrf1S5w6EQ01jeWlAGUhmNNyXLd-Q
      BOT_USERNAME: D_bb_D_bot
      ASSISTANT_NAME: votlx0
      GROUP_SUPPORT: V_O_T_l
      BOT_NAME: D_bb_D_bot
      OWNER_NAME: votlx
      ALIVE_NAME: votlx
      DEV_PHOTO: $DEV_PHOTO  # defaults to None
      BOT_PHOTO: $BOT_PHOTO  # defaults to None
